name: Docker Build and Push

on:
  workflow_run:
    workflows: ["SemVer Tag"]
    types:
      - completed

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set image tags
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

          echo "VERSION_LATEST=latest" >> $GITHUB_ENV
          echo "VERSION_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          echo $VERSION_LATEST
          echo $VERSION_TAG
